import { execFileSync } from 'node:child_process';
import test from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { MaintenanceBoard, type MaintenanceWorkRecord } from '../src/server/maintenance-board.js';

test('maintenance issues and detail use the office source even when the project has the same issue number', async (t) => {
  const root = mkdtempSync(path.join(tmpdir(), 'ao-maintenance-board-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const source = path.join(root, 'agent-office');
  const project = path.join(root, 'project');
  mkdirSync(source); mkdirSync(project);
  execFileSync('git', ['init', source]);
  execFileSync('git', ['remote', 'add', 'origin', 'git@github.com:team/agent-office.git'], { cwd: source });
  execFileSync('git', ['remote', 'add', 'upstream', 'https://github.com/upstream/agent-office.git'], { cwd: source });
  execFileSync('git', ['-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '--allow-empty', '-m', 'Unrelated upstream weather feature\n\nCloses #42'], { cwd: source });
  const shippedSha = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: source }).toString().trim();
  execFileSync('git', ['update-ref', 'refs/remotes/origin/main', shippedSha], { cwd: source });
  execFileSync('git', ['symbolic-ref', 'refs/remotes/origin/HEAD', 'refs/remotes/origin/main'], { cwd: source });
  const cli = path.join(root, 'gh');
  writeFileSync(cli, `#!${process.execPath}
const args = process.argv.slice(2);
const selected = args[0] === 'repo' ? args[2] : args[args.indexOf('--repo') + 1];
const office = process.cwd().endsWith('/agent-office') && selected === 'team/agent-office';
if (['repo', 'issue', 'pr'].includes(args[0]) && !office) { console.error('Wrong repository: upstream issue #42 does not exist'); process.exit(1); }
const title = office ? (require('node:fs').existsSync(process.cwd() + '/title.txt') ? require('node:fs').readFileSync(process.cwd() + '/title.txt', 'utf8') : 'Fix the maintenance closet') : 'Unrelated project issue';
if (args[0] === 'repo') console.log(JSON.stringify({nameWithOwner: office ? 'team/agent-office' : 'team/project'}));
else if (args[0] === 'issue' && args[1] === 'close') require('node:fs').writeFileSync(process.cwd() + '/closed.json', JSON.stringify(args));
else if (args[0] === 'issue' && args[1] === 'create') { require('node:fs').writeFileSync(process.cwd() + '/created.json', JSON.stringify({args, marker:process.env.CREATE_AS})); console.log('https://github.com/team/agent-office/issues/43'); }
else if (args[0] === 'issue' && args[1] === 'view') console.log(JSON.stringify({number:42,state:'OPEN',body:title,comments:[]}));
else if (args[0] === 'issue' && args.includes('open')) console.log(JSON.stringify([{number:42,title,state:'OPEN',url:'https://github.com/team/agent-office/issues/42'}]));
else console.log('[]');
`);
  chmodSync(cli, 0o755);
  const previous = process.env.PATH;
  process.env.PATH = `${root}${path.delimiter}${previous}`;
  t.after(() => { process.env.PATH = previous; });
  let workCommits: MaintenanceWorkRecord[] = [];
  const board = new MaintenanceBoard(() => {}, source, () => workCommits);
  await board.refresh();
  assert.equal(board.state.repo, 'team/agent-office');
  assert.equal(board.state.items[0].title, 'Fix the maintenance closet');
  assert.equal(board.state.items[0].doneBy, undefined, 'inherited closing keywords must not complete the fork issue');
  workCommits = [{ number: 42, status: 'paused', commits: [{ sha: shippedSha }] }];
  await board.refresh();
  assert.equal(board.state.items[0].doneBy, `commit ${shippedSha.slice(0, 7)} on main`, 'recorded Maintenance work still identifies shipped commits');
  assert.deepEqual(board.state.items[0].work, { status: 'paused', commits: 1 }, 'cards carry Maintenance status for every view');
  assert.equal(existsSync(path.join(source, 'closed.json')), false, 'interrupted work is never closed automatically');
  workCommits = [{ number: 42, status: 'review', commits: [{ sha: shippedSha }] }];
  await board.refresh();
  const closed = JSON.parse(readFileSync(path.join(source, 'closed.json'), 'utf8'));
  assert.ok(closed.includes('42') && closed.includes('team/agent-office'), 'finished work whose commits all shipped closes its issue');
  assert.ok(closed.some((a: string) => a.includes(shippedSha.slice(0, 7))), 'the closing comment names the shipped commits');
  rmSync(path.join(source, 'closed.json'));
  await board.refresh();
  assert.equal(existsSync(path.join(source, 'closed.json')), false, 'a close is attempted once, not every poll');
  workCommits = [];
  await board.refresh();
  assert.equal(board.state.items[0].doneBy, undefined, 'stale completion badges are cleared');
  assert.equal((await board.issue(42, 'reviewer')).body, 'Fix the maintenance closet');
  assert.match(await board.request(42), /Fix the maintenance closet/);
  assert.match(await board.request(42), /https:\/\/github.com\/team\/agent-office\/issues\/42/);
  writeFileSync(path.join(source, 'title.txt'), 'Updated issue title');
  assert.match(await board.request(42), /Updated issue title/);
  assert.equal(board.state.items[0].title, 'Updated issue title');
  await assert.rejects(board.request(42, true), /no longer queued on GitHub/);
  assert.equal(await board.claim(42), undefined);
  assert.equal((await board.create('Improve Maintenance', 'Keep ideas while it works', { env: { ...process.env, CREATE_AS: 'requester' } } as any)).number, 43);
  const created = JSON.parse(readFileSync(path.join(source, 'created.json'), 'utf8'));
  assert.equal(created.marker, 'requester');
  assert.ok(created.args.includes('team/agent-office'));
  assert.ok(created.args.includes('Keep ideas while it works'));
  await assert.rejects(board.create('', ''), /title/);
  await assert.rejects(board.issue(-1), /Bad issue number/);
  board.stop();
});

test('maintenance board refuses to fall back to upstream without a GitHub origin', async (t) => {
  const source = mkdtempSync(path.join(tmpdir(), 'ao-maintenance-no-origin-'));
  t.after(() => rmSync(source, { recursive: true, force: true }));
  execFileSync('git', ['init', source]);
  execFileSync('git', ['remote', 'add', 'upstream', 'https://github.com/upstream/agent-office.git'], { cwd: source });
  const board = new MaintenanceBoard(() => {}, source);
  await board.refresh();
  assert.match(board.state.error!, /GitHub origin remote/);
  await assert.rejects(board.request(42), /GitHub origin remote/);
});
